version: '2'
services:
  mongo:
    image: mongo:latest
    # ports:   # Uncomment these lines if you want to expose the MongoDB port locally on your host
    #  - "27017:27017"
  web:
    build: .
    ports:
     - "3000:3000"
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     